import { NextResponse } from 'next/server'
import { prismadb } from '@/lib/prismadb'
import { getSession } from '@/lib/auth'

export async function GET() {
    const session = await getSession()
    if (!session) return new NextResponse('Unauthorized', { status: 401 })

    try {
        const templates = await prismadb.proposalTemplate.findMany({
            where: { workspaceId: session.workspaceId },
            orderBy: { createdAt: 'desc' }
        })
        return NextResponse.json(templates)
    } catch (error) {
        console.error('[PROPOSALS_GET]', error)
        return new NextResponse('Internal Error', { status: 500 })
    }
}

export async function POST(req: Request) {
    const session = await getSession()
    if (!session) return new NextResponse('Unauthorized', { status: 401 })

    try {
        const body = await req.json()
        const { action, prompt, name, content } = body

        if (action === 'generate') {
            // MOCK AI GENERATION for now
            // In production, call OpenAI / Gemini here
            const generatedContent = `
# Proposal for ${prompt}

## Executive Summary
We are excited to submit this proposal for ${prompt}. Our team is dedicated to providing the best solution for your needs.

## Objectives
1. Understand client requirements
2. Deliver high-quality results
3. Ensure long-term success

## Timeline
- **Phase 1**: Discovery (1 Week)
- **Phase 2**: Implementation (2 Weeks)
- **Phase 3**: Review & Launch (1 Week)

## Pricing
Estimated cost: $5,000 - $10,000 depending on specific requirements.

## Next Steps
Please let us know if you would like to proceed with a formal agreement.

*Generated by Outflux AI*
            `
            return NextResponse.json({ content: generatedContent })
        }

        if (action === 'save') {
            const template = await prismadb.proposalTemplate.create({
                data: {
                    name,
                    content,
                    prompt,
                    workspaceId: session.workspaceId,
                    createdBy: session.id
                }
            })
            return NextResponse.json(template)
        }

        return new NextResponse('Invalid action', { status: 400 })

    } catch (error) {
        console.error('[PROPOSALS_POST]', error)
        return new NextResponse('Internal Error', { status: 500 })
    }
}
